version: '3.8'

services:
  frontend:
    build: ./frontend/resume-builder
    ports:
      - "4173:3000"
    restart: always

  backend:
    build: ./backend
    ports:
      - "8005:8005"
    restart: always
    env_file:
      - ./backend/.env
    # depends_on:
    #   - mongo

  # mongo:
  #   image: mongo
  #   restart: always
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo-data:/data/db

# volumes:
#   mongo-data:
